image:
  file: .gitpod.Dockerfile
checkoutLocation: '.'
workspaceLocation: 'content'
tasks:
  - name: Remove solutions
    command: |
      rm -rfv solutions/
ports:
  - port: 0-9999
    onOpen: notify
