FROM node:14.18-slim

# Copy the code inside the container image
COPY . /app

# Change working directory
WORKDIR /app

# Install requirements
RUN npm install && npm install -g serve

# Define environment variables to use with the image
ENV BACKEND_URL=""
ENV PORT=""

# Define port exposed by the app
EXPOSE 3000

ENTRYPOINT [ "/bin/bash" ]
CMD ["start.sh"]
